# Generated by Django 5.1.6 on 2025-03-08 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_shipping_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.shipping'),
            preserve_default=False,
        ),
    ]
