# Generated by Django 5.1.6 on 2025-03-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_order_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='products/default.png', upload_to='products/'),
            preserve_default=False,
        ),
    ]
